# _config.yml

# Site Settings
title: "React Starter Guide"
description: "Simple guide to help you on your React journey"
baseurl: "/react-starter-guide"
url: "https://keacluser.github.io"

# Build Settings

# Other settings...
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
