# _config.yml

# Site Settings
title: "React Starter Guide"
description: "Simple guide to help you on your React journey"
baseurl: "/react-starter-guide"
url: "https://keacluser.github.io"

# Build Settings
theme: "jekyll-theme-midnight"

# Other settings...
